name: docsify-nightly

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '37 3 * * *'

jobs:
  build:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          git clone https://github.com/docsifyjs/docsify.git
          cd docsify
          npm ci --ignore-scripts

      - name: Build docsify
        run: |
          cd docsify
          npm run build

      - name: Move files
        run: |
          cp -Rf docsify/lib ./
          rm -rf docsify
          git status

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: sy-records
          commit_user_email: 52o@qq52o.cn
          commit_message: Nightly release for docsify
