name: docsify-nightly

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '37 3 * * *'

jobs:
  build:
    runs-on: "ubuntu-latest"

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"

      - name: Clone & Build Docsify
        run: |
          set -e
          git clone https://github.com/docsifyjs/docsify.git
          cd docsify
          npm ci --ignore-scripts
          npm run build

      - name: Sync files
        run: |
          rsync -av --delete docsify/dist/ ./dist/
          rsync -av --delete docsify/src/ ./src/
          rm -rf docsify
          git status

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        id: auto-commit-action
        with:
          commit_user_name: sy-records
          commit_user_email: lufei@docsifyjs.org
          commit_message: Nightly release for docsify

      - name: Trigger publish workflow
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type":"trigger-publish"}'
