name: Publish NPM Package to GitHub Packages and npm

on:
  push:
    branches:
      - develop
    paths:
      - 'dist/**'
  workflow_dispatch:

jobs:
  publish:
    if: github.repository_owner == 'sy-records'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Generate nightly version
        run: |
          NIGHTLY_VERSION=5.0.0-nightly.$(git rev-parse --short HEAD)
          npm version $NIGHTLY_VERSION --no-git-tag-version

      - name: Authenticate with GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PUBLISH_GITHUB_TOKEN }}" > ~/.npmrc
          echo "registry=https://npm.pkg.github.com" >> ~/.npmrc

      - name: Test publish to GitHub Packages
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Testing publish to GitHub Packages..."
          npm publish --tag nightly --dry-run --registry=https://npm.pkg.github.com

      - name: Publish to GitHub Packages
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        run: npm publish --tag nightly --registry=https://npm.pkg.github.com

      - name: Authenticate with npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.PUBLISH_NPM_TOKEN }}" >> ~/.npmrc

      - name: Test publish to npm registry
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Testing publish to npm registry..."
          npm publish --tag nightly --dry-run --registry=https://registry.npmjs.org

      - name: Publish to npm registry
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        run: npm publish --tag nightly --access public --registry=https://registry.npmjs.org
